[General]
LastPlayedFile=file:///home/matt/Documentos/qbit/The Elusive Samurai S01 1080p Dual Audio WEBRip DD+ x265-EMBER/The.Elusive.Samurai.S01E01.1080p.Dual.Audio.WEBRip.DD+.x265-EMBER.mkv

[Playback]
SeekSmallStep=10

[Playlist]
Visible=true
