Counter=2

[Command_0]
Command=load-script "~/.config/haruna/scripts/skip_confirm.lua"
Order=0
OsdMessage=
Type=startup

[Command_1]
Command=script-message-to skip_confirm cancel_skip
Order=1
OsdMessage=
Type=shortcut
